server:
  port: 8001

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/staff_cms
    username: root
    password: root
  mvc:
    static-path-pattern: /static/**

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.lx.pojo


